CREATE TABLE IF NOT EXISTS `pricelist_import_batches` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `source_file_name` VARCHAR(255) NOT NULL,
  `stored_file_name` VARCHAR(255) NOT NULL,
  `raw_rows` INT(11) NOT NULL DEFAULT 0,
  `processed_rows` INT(11) NOT NULL DEFAULT 0,
  `matched_rows` INT(11) NOT NULL DEFAULT 0,
  `pricelist_only_rows` INT(11) NOT NULL DEFAULT 0,
  `product_only_rows` INT(11) NOT NULL DEFAULT 0,
  `changed_rows` INT(11) NOT NULL DEFAULT 0,
  `invalid_rows` INT(11) NOT NULL DEFAULT 0,
  `duplicate_rows` INT(11) NOT NULL DEFAULT 0,
  `conflict_rows` INT(11) NOT NULL DEFAULT 0,
  `status` VARCHAR(32) NOT NULL DEFAULT 'IMPORTED',
  `imported_by` BIGINT(20) DEFAULT NULL,
  `approved_by` BIGINT(20) DEFAULT NULL,
  `imported_at` DATETIME NOT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pricelist_import_batches_status` (`status`),
  KEY `idx_pricelist_import_batches_imported_at` (`imported_at`),
  KEY `idx_pricelist_import_batches_approved_at` (`approved_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `pricelist_import_items` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT(20) UNSIGNED NOT NULL,
  `row_number` INT(11) DEFAULT NULL,
  `kode_barang` VARCHAR(64) DEFAULT NULL,
  `deskripsi_raw` VARCHAR(255) DEFAULT NULL,
  `deskripsi_bersih` VARCHAR(191) NOT NULL,
  `supplier` VARCHAR(191) DEFAULT NULL,
  `new_price` INT(11) DEFAULT NULL,
  `new_price_2` INT(11) DEFAULT NULL,
  `new_price_3` INT(11) DEFAULT NULL,
  `tgl_info` VARCHAR(64) DEFAULT NULL,
  `keterangan_asal_info` TEXT DEFAULT NULL,
  `raw_payload` TEXT DEFAULT NULL,
  `source_rows` INT(11) NOT NULL DEFAULT 1,
  `product_id` BIGINT(20) DEFAULT NULL,
  `product_name` VARCHAR(191) DEFAULT NULL,
  `current_price` INT(11) DEFAULT NULL,
  `current_price_2` INT(11) DEFAULT NULL,
  `current_price_3` INT(11) DEFAULT NULL,
  `match_status` VARCHAR(32) NOT NULL DEFAULT 'INVALID',
  `change_status` VARCHAR(32) NOT NULL DEFAULT 'INVALID',
  `validation_message` TEXT DEFAULT NULL,
  `update_status` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `updated_by` BIGINT(20) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pricelist_import_items_batch` (`batch_id`),
  KEY `idx_pricelist_import_items_desc` (`deskripsi_bersih`),
  KEY `idx_pricelist_import_items_product` (`product_id`),
  KEY `idx_pricelist_import_items_match` (`match_status`),
  KEY `idx_pricelist_import_items_change` (`change_status`),
  KEY `idx_pricelist_import_items_update` (`update_status`),
  CONSTRAINT `fk_pricelist_import_items_batch`
    FOREIGN KEY (`batch_id`) REFERENCES `pricelist_import_batches` (`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
